### ISSUE TITLE
[FR] 大佬请开jellybean和kitkat分支，有开发者愿意提交PR贡献代码。

### ISSUE THREAD

**Issue by cqbf** [lizongying/my-tv-0#104]
### 提需求前請檢查

- [X] 已檢查過需求列表，沒有人提過相同需求

### 需求建議

https://github.com/vrichv/my-tv-0/tree/jellybean
https://github.com/vrichv/my-tv-0/tree/kitkat
开发者 @vrichv 已经兼容了4.2、4.3、4.4，并且很愿意提交PR贡献代码。
https://github.com/vrichv/my-tv-0/issues/2#issuecomment-2288664736

请大佬创建jellybean和kitkat分支，兼容4.x

**Comment by lizongying** [comment]
感謝@vrichv 安卓4的用戶可以直接在他的倉庫下載。
我會創建這兩個分支，目前我可能沒時間在這兩個分支上，希望有其他開發者貢獻代碼。

**Comment by lizongying** [comment]
@cqbf 已添加兩個新分支

**Comment by cqbf** [comment]
> @cqbf 已添加兩個新分支

谢谢大佬，我去告诉 @vrichv
