### ISSUE TITLE
1.3.7.13 目前电视一切正常。如果在手机上观看手机上面配置的话，怎么操作比较简便一些？

### ISSUE THREAD

**Issue by kevinandlee** [lizongying/my-tv-0#105]
### 提需求前請檢查

- [X] 已檢查過需求列表，沒有人提過相同需求

### 需求建議

1.3.7.13 目前看电视一切正常。如果在手机上面观看单手机配置的话，怎么操作比较简便一些？
可以给一个 一键复制编辑链接🔗吗？

**Comment by lizongying** [comment]
可以任意瀏覽器打開設置網址。

**Comment by lizongying** [comment]
http://局域網地址:34567
