### ISSUE TITLE
[BUG] my-tv-0.1.3.7.19-kitkat.apk

### ISSUE THREAD

**Issue by SuperBlackWednesday** [lizongying/my-tv-0#108]
### 提問題前請檢查

- [X] 已檢查過問題列表，沒有人提過相同問題
- [X] 軟件的最新版本依然沒有被修復

### 軟件版本

my-tv-0.1.3.7.19

### 電視品牌

tcl 85q10K

### Android版本

不知道 今年的电视

### 問題描述

能安装 但是进去没有频道  黑屏  就右上角显示个时间 没了

**Comment by lizongying** [comment]
如果是新電視建議用my-tv-0.1.3.7.15

根據自己的網絡狀況選擇不同的版本，
如移動用戶可以選擇下载 my-tv-0.1.3.7.15.china-mobile.apk
支持ipv6的用戶可以選擇下载 my-tv-0.1.3.7.15.ipv6.apk
其他用戶可以選擇下载 my-tv-0.1.3.7.15.apk（這個版本頻道比較雜亂，建議自行添加直播源）

如果無法觀看，可能直播源不符合當前的網絡。
另外，如之前已安裝，可以卸載後再安裝新版本，避免之前的緩存。如果要保留自己的配置，可以直接安裝。

每個版本只是內置測試源不同，功能一樣。都可以添加符合自己網絡的直播源。

**Comment by xuedingedemao215** [comment]
这个支持4.4的版本在4.4的盒子上也是黑屏；建议去掉内置直播源，让用户自行添加。能找到这个下载软件的添加直播源都不是问题。另节目预告建议在节目列表界面显示更多，目前仅显示当前节目预告。感谢提供这么好的app。

**Comment by zbby1987** [comment]
> 如果是新電視建議用my-tv-0.1.3.7.15
> 
> 根據自己的網絡狀況選擇不同的版本， 如移動用戶可以選擇下载 my-tv-0.1.3.7.15.china-mobile.apk 支持ipv6的用戶可以選擇下载 my-tv-0.1.3.7.15.ipv6.apk 其他用戶可以選擇下载 my-tv-0.1.3.7.15.apk（這個版本頻道比較雜亂，建議自行添加直播源）
> 
> 如果無法觀看，可能直播源不符合當前的網絡。 另外，如之前已安裝，可以卸載後再安裝新版本，避免之前的緩存。如果要保留自己的配置，可以直接安裝。
> 
> 每個版本只是內置測試源不同，功能一樣。都可以添加符合自己網絡的直播源。

您说的移动用户，
是指用手机播放的用户？
还是指用些中国移动手机sim卡的用户

**Comment by lizongying** [comment]
如果安卓版本高於4.4 [v1.3.8.11](https://github.com/lizongying/my-tv-0/releases/tag/v1.3.8.11)
如果安卓版本4.4 [v1.3.8.14-kitkat](https://github.com/lizongying/my-tv-0/releases/tag/v1.3.8.14-kitkat)
