### ISSUE TITLE
[BUG] 电视上打开APP后在屏幕上边沿会有个“从顶部向下滑动即可退出全屏模式。”的弹窗，无法选中关闭。

### ISSUE THREAD

**Issue by Welding** [lizongying/my-tv-0#109]
### 提問題前請檢查

- [X] 已檢查過問題列表，沒有人提過相同問題
- [X] 軟件的最新版本依然沒有被修復

### 軟件版本

0.1.3.7.19

### 電視品牌

TCL

### Android版本

4.4

### 問題描述

电视上打开APP后在屏幕上边沿会有个“从顶部向下滑动即可退出全屏模式。”的弹窗，无法选中关闭。
![603f1801105c426e0a4d5fd01ced87b](https://github.com/user-attachments/assets/b29dd10e-56b0-4293-b33f-f4c211959fc4)

**Comment by lizongying** [comment]
等一段時間就會消失，我在一個盒子上復現了。沒想到原因，暫時就不改了。

**Comment by xisohi** [comment]
第一次安装软件会提示，应该是连上鼠标点一下
ok以后就不会再出现了，

**Comment by lizongying** [comment]
已修復 [v1.3.8.14-kitkat](https://github.com/lizongying/my-tv-0/releases/tag/v1.3.8.14-kitkat)]
