### ISSUE TITLE
[BUG] json格式文件频道导入错误 

### ISSUE THREAD

**Issue by youcannotseemeagain** [lizongying/my-tv-0#113]
### 提問題前請檢查

- [X] 已檢查過問題列表，沒有人提過相同問題
- [X] 軟件的最新版本依然沒有被修復

### 軟件版本

最新版

### 電視品牌

其他

### Android版本

其他

### 問題描述

我有一些m3u8源，但是这些源需要使用referer访问，所以我根据操作提示使用了json格式的配置并使用上传文件的方式导入。但是不管我如何定义修改json格式（即使是示例给出的json文件），导入总是提示频道导入错误，我不知道是哪里出了问题。

问题1：能否使用其他方式来配置Head头，或者APK能否设置一个全局的Head头？
问题2：我不知道json哪里错了，只要导入文件就会提示频道导入错误

给出我的json

[{
	"group": "test",
	"logo": "",
	"name": "test",
	"title": "test",
	"uris": [
		"https://tvshow.scgchc.com/hdlive/sctv58f9fb5888dedbe0c6a1b/1.m3u8?auth_key=2705542318-1838871373124812802-0-5933b34bb25ee2c574a6689011ac2792"
	],
	"headers": {
		"referer": "https://www.sctv.com/"
	}
}]

**Comment by lizongying** [comment]
<img width="404" alt="image" src="https://github.com/user-attachments/assets/ca7e185d-5ef4-4134-9afd-ba98b3ba4dcd">
是不是直接複製的文本？我在v1.3.7.16增加了直接文本的支持，自己試了，你的這個地址可以播放。
