### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ni7ht** [lizongying/my-tv-0#12]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

v1.0.1

### Bug 描述

最新的[my-tv-0]1.05，直播画面加载很慢，切换频道特别卡顿，会延迟几十秒甚至，对比my-tv 1.7.6秒切换差距很大，同一网络设备条件下测试。

### 预期行为

直播画面秒加载

### 实际行为

进去一个频道画面卡住几十秒没有声音

### 复现步骤

正常使用即可

### UI / OS

斐讯N1

### Android 版本

7.1.2

**Comment by lizongying** [comment]
這個項目建議使用自定義視頻源，內置的只作測試使用
