### ISSUE TITLE
[FR] 建议发新版时增加移动网络版

### ISSUE THREAD

**Issue by dairui2** [lizongying/my-tv-0#130]
### 提需求前請檢查

- [X] 已檢查過需求列表，沒有人提過相同需求

### 需求建議

1. 建议发新版时增加移动网络版
2. 感谢李老师一如既往的考虑移动网络用户的局限性

**Comment by lizongying** [comment]
後面可能不再單獨出特定網絡版本了，因為各地區可能還有差異。可以嘗試切換一下視頻源，也許有適合自己網絡的視頻源。

**Comment by dairui2** [comment]
已经试过了切换视频源，mytv0自带的20个视频源只有2个显示请求节目成功，但是依然黑屏，啥也不显示，其他视频源显示请求节目失败。我是移动网络
