### ISSUE TITLE
建议增加上下划换台的功能[FR] 

### ISSUE THREAD

**Issue by gdwengf** [lizongying/my-tv-0#14]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

上下划换台有利平板操作

**Comment by lizongying** [comment]
支持的，建議在中間區域上下滑，左右可能分配給聲音和亮度

**Comment by gdwengf** [comment]
老大，你原来的源都去掉了吗？能给我吗？

李宗英 ***@***.***> 于 2024年4月16日周二 13:06写道：

**Comment by lizongying** [comment]
@gdwengf 不能用了
