### ISSUE TITLE
❗请求❗ 加入 每次打开都是CCTV1❗[FR] 

### ISSUE THREAD

**Issue by StevenBaoZou** [lizongying/my-tv-0#15]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

❗请求❗ 加入 每次打开都是CCTV1 这个选项❗
强迫症患者真的需要每次打开都是CCTV1❗ 

### 解决方案

加入 每次打开都是CCTV1 这个选项，或者单独出一个每次打开都是CCTV1版本，感谢作者！！

### 额外信息

太感谢作者了！会赞赏！！！

**Comment by lizongying** [comment]
最新版可以設置默認頻道
