### ISSUE TITLE
请问如何自定义直播源？我怎么都搞不定，就说不符合要求，多谢多谢 

### ISSUE THREAD

**Issue by webgan** [lizongying/my-tv-0#16]
我想在你的基础上修改，看看能不能配置成功，多谢
我的是：
http://192.168.86.14:8000/0
 不知道对不对

**Comment by webgan** [comment]
![11](https://github.com/lizongying/my-tv-0/assets/55076467/ea7f8a00-3e28-4da4-9fe0-91207f1c6743)
就是这个，但是就是一直配置不到my-tv-0里面

**Comment by webgan** [comment]
![22](https://github.com/lizongying/my-tv-0/assets/55076467/cb0d54cc-9241-46fc-b46d-bfa98afba8e0)
这么个情况，

**Comment by lizongying** [comment]
1. 需要點擊 “輸出.json”。目前我的電視·〇僅支持json格式，而看你的輸入後綴是.m3u
2. 不必寫 “http://”，應該不影響，忘記試沒試過了，不過我沒寫“http://” 
3. 遙控器左鍵到確認，確認即可

**Comment by webgan** [comment]
多谢您的回复，我点击过【输出json】，但是没有任何输出，不知什么原因
![1351712885372_ pic](https://github.com/lizongying/my-tv-0/assets/55076467/8e8bc6c0-6e65-4e2a-a440-1f2043d10024)

**Comment by webgan** [comment]
三个终端都试过，（华为matepad-T5、当贝H3、海信TV65E8K）都不行，麻烦您了

**Comment by dyccsxg** [comment]
> 三个终端都试过，（华为matepad-T5、当贝H3、海信TV65E8K）都不行，麻烦您了

https://gitee.com/usm/notes/raw/master/tv/channels.json

试下这个，这是我用来测试的，和默认的一样

**Comment by ccav14** [comment]
不能在模拟器上测试吗，我用模拟器不管怎么加什么地址app都会闪退，楼上这个也不行

**Comment by lizongying** [comment]
> 多谢您的回复，我点击过【输出json】，但是没有任何输出，不知什么原因 ![1351712885372_ pic](https://private-user-images.githubusercontent.com/55076467/321827481-8e8bc6c0-6e65-4e2a-a440-1f2043d10024.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzgwMDEsIm5iZiI6MTcxMzE3NzcwMSwicGF0aCI6Ii81NTA3NjQ2Ny8zMjE4Mjc0ODEtOGU4YmM2YzAtNmU2NS00ZTJhLWE0NDAtMWYyMDQzZDEwMDI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDEwNDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMmVhN2ExZDM5MGU1NzU0ZDlmNDBlMGY1OTU5NDk3NzA5MTBmMWQwZTE5OWE4ZjE3MGUwM2NiMWM3Y2M1N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WzVlIFZgyLUP_G-XZgpFUtLYkA51vnBCNwvpTCJv7h8)

可能這個m3u文件格式不對，或者我解析的不對。方便的話貼出下部分內容。

**Comment by linzzzzllll** [comment]
不是很想得明白，这样添加直播源？真的很麻烦，不可以像TVBOX那种手机扫二维码添加进去吗，是有什么考虑呢

**Comment by webgan** [comment]
> > 多谢您的回复，我点击过【输出json】，但是没有任何输出，不知什么原因 ![1351712885372_ pic](https://private-user-images.githubusercontent.com/55076467/321827481-8e8bc6c0-6e65-4e2a-a440-1f2043d10024.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzgwMDEsIm5iZiI6MTcxMzE3NzcwMSwicGF0aCI6Ii81NTA3NjQ2Ny8zMjE4Mjc0ODEtOGU4YmM2YzAtNmU2NS00ZTJhLWE0NDAtMWYyMDQzZDEwMDI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDEwNDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMmVhN2ExZDM5MGU1NzU0ZDlmNDBlMGY1OTU5NDk3NzA5MTBmMWQwZTE5OWE4ZjE3MGUwM2NiMWM3Y2M1N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WzVlIFZgyLUP_G-XZgpFUtLYkA51vnBCNwvpTCJv7h8)
> 
> 可能這個m3u文件格式不對，或者我解析的不對。方便的話貼出下部分內容。

多谢多谢，您的新版本107已经可以添加txt源了，完美。完全满足了看电视的需求，再次感谢🙏

**Comment by webgan** [comment]
问题解决，感谢感谢🙏

**Comment by psumycom** [comment]
> 问题解决，感谢感谢🙏

我把所有回复都看完了还是不明白怎么添加自定义源，能帮助一下吗？
