### ISSUE TITLE
[FR] ui换一下

### ISSUE THREAD

**Issue by gonjudaren** [lizongying/my-tv-0#2]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

ui不好看   增加美观

### 解决方案

![R-C](https://github.com/lizongying/my-tv-0/assets/142286774/681a13b9-0d7c-4f82-b2b5-009477b60374)
跟图片这样子差不多

**Comment by zbby1987** [comment]
你这解决方案的ui更差

**Comment by linzzzzllll** [comment]
哈哈很经典很有意思

**Comment by lizongying** [comment]
後面倒是出這麼一個皮膚，高低得收費！
