### ISSUE TITLE
1.07安装后无法播放  都是黑屏 [BUG] 

### ISSUE THREAD

**Issue by kiben2010** [lizongying/my-tv-0#20]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

v1.0.1

### Bug 描述

1.07所有台黑屏 无法播放  之前1.06可以看  

### 预期行为

可以正常播放

### 实际行为

黑屏

### UI / OS

evpad10P

### Android 版本

10

**Comment by suweiteng** [comment]
你添加自己的源之后还是黑屏吗？我添加源之前是黑屏，添加后正常播放。

**Comment by kiben2010** [comment]
我没添加源  必须要自己添加吗

**Comment by suweiteng** [comment]
个人理解作者创立这个项目的目的就是让大家可以自定义源，如果没有自己的源的话，那应该使用作者的另一个my-tv项目。

**Comment by lizongying** [comment]
可以自己添加視頻源
