### ISSUE TITLE
[BUG] 只有卫视和国际频道没有央视频道，并且卫视黑屏不显示

### ISSUE THREAD

**Issue by psumycom** [lizongying/my-tv-0#23]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

v1.0.1

### Bug 描述

用的最新版本1.1.0，所有的卫视都是黑屏也没有声音，央视不见了，只有国际频道能看

### 预期行为

恢复央视和卫视

### 实际行为

现在只能看国际频道了

### UI / OS

网络机顶盒

### Android 版本

9

**Comment by lizongying** [comment]
請自定義直播源，如不會可以使用[我的電視](https://github.com/lizongying/my-tv)
