### ISSUE TITLE
求直播源

### ISSUE THREAD

**Issue by kiben2010** [lizongying/my-tv-0#24]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

现在的版本没有源就是黑屏，无法观看，有好用的直播源的兄弟姐妹分享一下 拜谢。

**Comment by psumycom** [comment]
我也想知道源在哪里找？有一个能自定义源的软件但手里没有源就没有用了，哪位哥哥能分享一下源在哪里找？

**Comment by wangyupo** [comment]
没源还想看，为什么不用my-tv呢

**Comment by AppleMate60pro** [comment]
没有稳定的源，还不如就用内之源的，除非你们喜欢折腾，当然通用版频繁更新也是挺折腾的，现在我都是装来玩玩，放在电视上看不现实

**Comment by AppleMate60pro** [comment]
> 我也想知道源在哪里找？有一个能自定义源的软件但手里没有源就没有用了，哪位哥哥能分享一下源在哪里找？

我给你一个综合台的源，很稳定就一个

**Comment by SRmonologue** [comment]
https://raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u
