### ISSUE TITLE
小米盒子提示安装失败

### ISSUE THREAD

**Issue by starkong2022** [lizongying/my-tv-0#25]
有没有什么解决方案

**Comment by zbby1987** [comment]
你安卓几的盒子？安卓6的都能安啊

**Comment by maciakng** [comment]
我安卓5的装不上

**Comment by zbby1987** [comment]
目前最低只支持到安卓6，
4和5安不了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月18日(周四) 下午4:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [lizongying/my-tv-0] 小米盒子提示安装失败 (Issue #25)




 
我安卓5的装不上

**Comment by lizongying** [comment]
最低版本設置到了安卓5，@starkong2022 你可以試試

**Comment by starkong2022** [comment]
感谢大佬
