### ISSUE TITLE
能否支持本地视频源？[FR] 

### ISSUE THREAD

**Issue by wangyupo** [lizongying/my-tv-0#27]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

当我使用安卓平板时，因为大陆众所周知的原因，线上的m3u8、m3u都被屏蔽，或频繁换地址。我通常在自己平板的内存储存一份.m3u8、.m3u、.txt文件。我希望可以导入本地的.m3u8、.m3u、.txt文件，来实现观看直播功能。

**Comment by lizongying** [comment]
後面會加入。
你可以試試用[my-tv-server](https://github.com/lizongying/my-tv-server)轉化成本地地址，反正只需要配置一次。

**Comment by gdwengf** [comment]
> 後面會加入。 你可以試試用[my-tv-server](https://github.com/lizongying/my-tv-server)轉化成本地地址，反正只需要配置一次。

希望早点可用本地源。那个服务器用不起来

**Comment by AppleMate60pro** [comment]
> > 後面會加入。 你可以試試用[my-tv-server](https://github.com/lizongying/my-tv-server)轉化成本地地址，反正只需要配置一次。
> 
> 希望早点可用本地源。那个服务器用不起来
很简单，还不如直接TXT 或者m3ub 文件挂载，用线路更好

**Comment by gdwengf** [comment]
> > > 後面會加入。 你可以試試用[my-tv-server](https://github.com/lizongying/my-tv-server)轉化成本地地址，反正只需要配置一次。
> > 
> > 
> > 希望早点可用本地源。那个服务器用不起来
> > 很简单，还不如直接TXT 或者m3ub 文件挂载，用线路更好

看不懂什么办

**Comment by lizongying** [comment]
最新版已支持
