### ISSUE TITLE
[FR] 恳请支持RTSP流的节目源

### ISSUE THREAD

**Issue by lfm09** [lizongying/my-tv-0#28]
我这的节目源都是类似rtsp://***/*.smil这种格式，试了几次都没法播放，希望能尽快支持，谢谢老大

**Comment by lizongying** [comment]
公網可以訪問嗎，可以發給我試試 lizongying@msn.com

**Comment by lfm09** [comment]
> 公網可以訪問嗎，可以發給我試試 [lizongying@msn.com](mailto:lizongying@msn.com)

电信IPTV节目源，已发邮箱

**Comment by yalicez** [comment]
1.16联通的rtsp节目源也不支持

**Comment by lizongying** [comment]
可以試試 1.2.8

**Comment by lfm09** [comment]
> 可以試試 1.2.8

老大，还是不行哦
