### ISSUE TITLE
[FR] UI存在的几个问题及建议

### ISSUE THREAD

**Issue by iseku** [lizongying/my-tv-0#30]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

1. 屏幕右上角的时间显示不全，分钟少1位，并且在设置中关闭显示时间后，每次启动还是会显示时间。
2. 选台菜单的遥控器(键盘)操作存在一些问题（鼠标操作没有问题）：
    (1) 打开频道菜单后没有定位到当前频道，建议如果是当前分组的就定位到当前频道，如果不是当前分组的就定位到第一个频道
    (2) 分组栏选单显示不清晰，只是文字由灰变白，不靠近看不清选的哪个，建议跟频道选择一样为选中项加个背景色
    (3) 在分组栏按右键进入频道分组后，分组栏会隐藏，再按左键才会再打开，频道列表跳来跳去的感觉很难受，建议跟鼠标操作一样不要做隐藏，在软件实现上应该也会更简单
    (4) 频道栏在用上下键选择频道时，如果到顶或到底后继续操作会循环跳到频道列表底部或顶部，在实现上似乎存在一些问题，首先是跳转后没有显示选择条，而是需要再按上下键才显示，其次定位到的频道位置也不对
    (5) 反复用遥控器操作频道菜单后偶尔会引起程序崩溃退出
    (6) 频道菜单的显示建议做超时处理，比如10秒没有操作就自动关闭
3. 右键弹出配置菜单的设计很容易产生误操作，建议合并到频道菜单作为分组栏的一个选项
4. 程序重启后，配置菜单的“配置地址”内容不再显示，建议显示原先配置的网址
5. 保存最后观看频道的功能，感觉是在程序正常退出时做的保存操作，但是在电视机或者机顶盒上一般都是直接关电而不是退出程序后再关机，这时候就无法正确保存，建议在每次换台后进行保存
![IMG_3013](https://github.com/lizongying/my-tv-0/assets/46520618/e1d19dc8-99c2-47d1-9cb3-169ce2ea9c46)

**Comment by lizongying** [comment]
很好的建議

**Comment by lizongying** [comment]
1、4、5 會最新版修復。3先看看大家的反饋。

**Comment by lizongying** [comment]
2.1 已解決
2.2 2.3 暫時維持不變，應該不影響操作
2.4 已解決
2.5 暫時沒發現
2.6 會自動關閉的
