### ISSUE TITLE
[BUG] m3u源提示无法读取频道

### ISSUE THREAD

**Issue by shuohao** [lizongying/my-tv-0#31]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

v1.0.1

### Bug 描述

提示无法读取频道，m3u源：https://mirror.ghproxy.com/https://raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u

### 预期行为

能正常加载自定义m3u源频道

### 实际行为

提示 无法读取频道

### UI / OS

xiaomi 12pro hyper os

### Android 版本

12

**Comment by lizongying** [comment]
在 1.1.3 已修復

**Comment by shuohao** [comment]
> 在 1.1.3 已修復

高效 亲测可用  谢谢老板
