### ISSUE TITLE
[FR] 源地址输入到安卓tv版太痛苦了。

### ISSUE THREAD

**Issue by kimwang1978** [lizongying/my-tv-0#32]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

源地址太长，用遥控器输入到安卓tv版太痛苦了。

### 解决方案

有没有类似tvbox那种提供一个qrcode，手机读取后从手机直接推送地址的功能？

**Comment by lizongying** [comment]
会加入

**Comment by devXiaoL** [comment]
@kimwang1978 如果可以使用 adb 连接电视，可以先定位到输入框，然后用 adb shell input text "url地址"  进行输入

**Comment by kimwang1978** [comment]
@devXiaoL 好的，多谢提供思路，先试试看。

**Comment by lizongying** [comment]
如果不需要更新，可以文件下載下來，用my-tv-server 轉發一下。
最新版app加了内置的服务器，局域网可以访问配置。

**Comment by kimwang1978** [comment]
> 如果不需要更新，可以文件下載下來，用my-tv-server 轉發一下。 最新版app加了内置的服务器，局域网可以访问配置。

好的，我来试试，多谢！

**Comment by iseku** [comment]
可以装个小盒精灵 TVRemoteIME，除了能手机输入还可以上传安装软件，挺方便的

**Comment by AppleMate60pro** [comment]
明明有TVbox非要人家也搞一个这个

**Comment by kimwang1978** [comment]
> 明明有TVbox非要人家也搞一个这个

严重了，只是提个需求帮助完善，搞不搞还是看作者，可选的东西当然不止tvbox，多的是。

**Comment by jackie-wayland** [comment]
@lizongying 不能配置为本地的m3u文件吗

**Comment by shuohao** [comment]
> 明明有TVbox非要人家也搞一个这个

tvbox貌似不支持m3u格式地址吧

**Comment by lizongying** [comment]
> @lizongying 不能配置为本地的m3u文件吗

現在可以設置本地的文件

**Comment by lizongying** [comment]
最新版已支持二維碼
