### ISSUE TITLE
[BUG] 不能播放代理直播源

### ISSUE THREAD

**Issue by maciakng** [lizongying/my-tv-0#33]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

如题，格式为：河南卫视,http://x.x.x.x.x/henan.php?id=hnws
黑屏转圈无法播放

### 预期行为

希望能修复

### 实际行为

1

### UI / OS

小米

### Android 版本

12

**Comment by lizongying** [comment]
具體格式，完整一點

**Comment by lizongying** [comment]
什麼是代理直播源？是支持播放地址跳轉的。

**Comment by xuedingedemao215** [comment]
http://10.255.126.3:8006/AHBKLIVE/00000001000000050000000000000152
这样式的联通iptv的源也无法播放，希望修复下 
附件改下后缀名可以用记事本打开
![00000001000000050000000000000152](https://github.com/lizongying/my-tv-0/assets/167168090/f6ad6a69-fc43-4ec3-bc41-4a0b2d66666e)

**Comment by maciakng** [comment]
http://tvbox.mohuajz.eu.org/tv/ysp.php?id=1   比如这个用其他播放器可以播放这个不行 @lizongying

**Comment by liqiangsky** [comment]
> > http://tvbox.mohuajz.eu.org/tv/ysp.php?id=1 比如这个用其他播放器可以播放这个不行 @lizongying
> 
> 我是播放不了。有人可以播放嗎？

不能播放

**Comment by HonPhinXu1995** [comment]
我也碰到黑屏转圈无法播放的问题了，我使用的版本是v1.1.6

我使用的直播源地址：[https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/iptv.m3u](url)
（经测试 以上直播源我使用APTV以及POTPLAYER播放器都能成功播放）

但将此直播源导入mt-tv-0后，提示导入成功，每个频道都是黑屏转圈，如下图所示：
![1](https://github.com/lizongying/my-tv-0/assets/63764520/9024323b-c3c1-4eed-84fb-211d62b820bc)
![2](https://github.com/lizongying/my-tv-0/assets/63764520/08ed5a2e-942f-4f0d-a42a-1725e6e49526)

**Comment by HonPhinXu1995** [comment]
我也碰到黑屏转圈无法播放的问题了，我使用的版本是v1.1.6

我使用的直播源地址：[https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/aishang.m3u](url)
（经测试 以上直播源的CCTV-4K我使用APTV能成功播放）
![1](https://github.com/lizongying/my-tv-0/assets/63764520/80c081ed-447f-4e90-9c8a-841bb46a3a2e)
CCTV-4K原地址如下：
`#EXTM3U
#EXTINF:-1,tvg-id="CCTV4K" tvg-name="CCTV4K" tvg-logo="https://epg.112114.xyz/logo/CCTV4K.png" group-title="4K频道",CCTV-4K
http://159.75.85.63:5679/cctv4k.php`

但将此直播源导入mt-tv-0后，提示导入成功，每个频道都是黑屏转圈，如下图所示：
![2](https://github.com/lizongying/my-tv-0/assets/63764520/63eb4c9b-63d3-4acd-85e9-b56fb736944d)
![3](https://github.com/lizongying/my-tv-0/assets/63764520/ed321d86-e8fe-4b63-b102-7f234ed6112d)

**Comment by linzzzzllll** [comment]
http://www.stream-link.org/stream-link.m3u 不行

**Comment by xuedingedemao215** [comment]
> > http://10.255.126.3:8006/AHBKLIVE/00000001000000050000000000000152 这样式的联通iptv的源也无法播放，希望修复下 附件改下后缀名可以用记事本打开 ![00000001000000050000000000000152](https://private-user-images.githubusercontent.com/167168090/327988499-f6ad6a69-fc43-4ec3-bc41-4a0b2d66666e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzQzODEsIm5iZiI6MTcxNTE3NDA4MSwicGF0aCI6Ii8xNjcxNjgwOTAvMzI3OTg4NDk5LWY2YWQ2YTY5LWZjNDMtNGVjMy1iYzQxLTRhMGIyZDY2NjY2ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxMzE0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzAzMTYyMzk5Yzg5NmQzODBkYjc2ZDk4NTllNjQ0M2VlZDRiMjkzOTA4ZjExMjdmMWU4NTMwMjY5Y2RkOTIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2CdC547dvHqmUoy3j0YoX1VEY1PWTT-YwpWimjopulU)
> 
> 我這連接不上

这是联通的内网单播地址；打开后具体内容如下：

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:29536554
#EXT-X-PROGRAM-DATE-TIME:2024-05-11T06:17:29Z
#EXTINF:10,10625384
http://10.40.27.25:8114/LIVES/1715408249_0003296893_0000000063.ts?FvSeid=7185419b66dfa1a8&Fsv_filetype=2&Provider_id=AHBKLIVE&Pcontent_id=00000001000000050000000000000152&Fsv_CMSID=AHBK&Fsv_Sd=10&Fsv_Seq=29536554&Fsv_otype=0&UserID=&stbid=
#EXT-X-PROGRAM-DATE-TIME:2024-05-11T06:17:39Z
#EXTINF:10,10625384
http://10.40.27.25:8114/LIVES/1715408259_0003296893_0000000064.ts?FvSeid=7185419b66dfa1a8&Fsv_filetype=2&Provider_id=AHBKLIVE&Pcontent_id=00000001000000050000000000000152&Fsv_CMSID=AHBK&Fsv_Sd=10&Fsv_Seq=29536555&Fsv_otype=0&UserID=&stbid=
#EXT-X-PROGRAM-DATE-TIME:2024-05-11T06:17:49Z
#EXTINF:10,10625384
http://10.40.27.25:8114/LIVES/1715408269_0003296893_0000000065.ts?FvSeid=7185419b66dfa1a8&Fsv_filetype=2&Provider_id=AHBKLIVE&Pcontent_id=00000001000000050000000000000152&Fsv_CMSID=AHBK&Fsv_Sd=10&Fsv_Seq=29536556&Fsv_otype=0&UserID=&stbid=
#EXT-X-PROGRAM-DATE-TIME:2024-05-11T06:17:59Z
#EXTINF:10,10625384
http://10.40.27.25:8114/LIVES/1715408279_0003296893_0000000066.ts?FvSeid=7185419b66dfa1a8&Fsv_filetype=2&Provider_id=AHBKLIVE&Pcontent_id=00000001000000050000000000000152&Fsv_CMSID=AHBK&Fsv_Sd=10&Fsv_Seq=29536557&Fsv_otype=0&UserID=&stbid=
#EXT-X-PROGRAM-DATE-TIME:2024-05-11T06:18:09Z
#EXTINF:10,10625384
http://10.40.27.25:8114/LIVES/1715408289_0003296893_0000000067.ts?FvSeid=7185419b66dfa1a8&Fsv_filetype=2&Provider_id=AHBKLIVE&Pcontent_id=00000001000000050000000000000152&Fsv_CMSID=AHBK&Fsv_Sd=10&Fsv_Seq=29536558&Fsv_otype=0&UserID=&stbid=
#EXT-X-PROGRAM-DATE-TIME:2024-05-11T06:18:19Z
#EXTINF:10,10624068
http://10.40.27.25:8114/LIVES/1715408299_0003296893_0000000068.ts?FvSeid=7185419b66dfa1a8&Fsv_filetype=2&Provider_id=AHBKLIVE&Pcontent_id=00000001000000050000000000000152&Fsv_CMSID=AHBK&Fsv_Sd=10&Fsv_Seq=29536559&Fsv_otype=0&UserID=&stbid=

**Comment by lizongying** [comment]
@linzzzzllll http://www.stream-link.org/stream-link.m3u 401 Authorization Required

**Comment by lizongying** [comment]
@linzzzzllll 你用什麼播放器可以看？

**Comment by linzzzzllll** [comment]
> @linzzzzllll 你用什麼播放器可以看？
> 

影视仓

**Comment by linzzzzllll** [comment]
> @linzzzzllll 你用什麼播放器可以看？
> 

需要香港线路

**Comment by maciakng** [comment]
http://kang.mhfs.eu.org/tv/hebei.php?id=hbws    这个tvbox，DIYP都可以播放，播放器链接https://tansuo.lanzouo.com/ilBOj1kywj2j  、 https://sharerw.lanzoui.com/b0aevufxe    @lizongying

**Comment by linzzzzllll** [comment]
> @linzzzzllll http://www.stream-link.org/stream-link.m3u 401 Authorization Required
> 
> 

新版可以了！不知道是错觉还是怎么样，还很流畅比我所用的其他应用都流畅，牛逼！

**Comment by linzzzzllll** [comment]
> > @linzzzzllll http://www.stream-link.org/stream-link.m3u 401 Authorization Required
> > 
> > 
> 
> 新版可以了！不知道是错觉还是怎么样，还很流畅比我所用的其他应用都流畅，牛逼！

能不能提这个源的几个凤凰台出来到 mytv

**Comment by linzzzzllll** [comment]
> > > @linzzzzllll http://www.stream-link.org/stream-link.m3u 401 Authorization Required
> > > 
> > > 
> > 
> > 新版可以了！不知道是错觉还是怎么样，还很流畅比我所用的其他应用都流畅，牛逼！
> 
> 能不能提这个源的几个凤凰台出来到 mytv

测试了下还是不是很行，第二次进去就黑屏了

**Comment by linzzzzllll** [comment]
> > @linzzzzllll http://www.stream-link.org/stream-link.m3u 401 Authorization Required
> > 
> > 
> 
> 新版可以了！不知道是错觉还是怎么样，还很流畅比我所用的其他应用都流畅，牛逼！

这个源换台有问题

**Comment by lizongying** [comment]
> > > > @linzzzzllll http://www.stream-link.org/stream-link.m3u 401 Authorization Required
> > > 
> > > 
> > > 新版可以了！不知道是错觉还是怎么样，还很流畅比我所用的其他应用都流畅，牛逼！
> > 
> > 
> > 能不能提这个源的几个凤凰台出来到 mytv
> 
> 测试了下还是不是很行，第二次进去就黑屏了

我的電視用的源都是官方源，就是要保證安全、保證播放效果，儘管過程很艱辛。
直接的iptv線路，本來我是不想用的，也沒有技術挑戰，既然大家有這個需求，還是新開了我的電視·〇
還有很多都是轉發的線路，誰能保證安全性？中途加幾個廣告或者來段黃賭毒，怎麼處理？

**Comment by lizongying** [comment]
在1.2.3解決了
