### ISSUE TITLE
[BUG] 使用遥控器上下切换频道后，返回频道列表选中的光标会丢失

### ISSUE THREAD

**Issue by kt600** [lizongying/my-tv-0#34]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

你好，反馈一个使用体验问题：使用遥控器上下切换频道后，返回频道列表选中的光标会丢失，看样子频道的列表没有更新选中的光标位置

### 预期行为

希望每次切换遥控器切换频道按键，返回频道列表的光标会跟随切换频道的位置

### 实际行为

光标不见了

### UI / OS

海信智能电视、腾讯极光盒子

### Android 版本

10

**Comment by lizongying** [comment]
有這個問題，在嘗試解決

**Comment by lizongying** [comment]
> > 有這個問題，在嘗試解決
> > release v1.1.8 resolved ?

應該可以了
