### ISSUE TITLE
[BUG] 在极米投影上使用遥控器按任何按键都会弹出设置页且无法取消

### ISSUE THREAD

**Issue by shuohao** [lizongying/my-tv-0#35]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

在极米投影上使用遥控器按任何按键 包括上下换台或者左右键音量上下以及返回键确认键菜单键都会弹出设置页
![db7796674b1a42f3da2b03a3df3f3dc](https://github.com/lizongying/my-tv-0/assets/4637107/8d96d707-60f7-416a-a751-f8b0d277c290)

### 预期行为

正常换台

### 实际行为

出现设置页面，就是那个输入源那个页面

### UI / OS

极米GMUI5.0

### Android 版本

8

### 额外信息

 今天下载源码看了一天也没有发现是什么问题，Android studio模拟是正常的，但是安装到极米上就不正常，但是最新版的my-tv却是正常的，这就很奇怪  @lizongying

**Comment by lizongying** [comment]
試試最新版，我去掉了一個unknown 的keycode，只能是這個原因了。

**Comment by shuohao** [comment]
> 試試最新版，我去掉了一個unknown 的keycode，只能是這個原因了。

1.2.2版本试了 还是不行  神奇的是my-tv我看代码也是有KEYCODE_UNKNOWN但是是正常的

**Comment by shuohao** [comment]
> 試試最新版，我去掉了一個unknown 的keycode，只能是這個原因了。

我打了一下toast
![image](https://github.com/lizongying/my-tv-0/assets/4637107/bb7c48c2-9fa6-4ab5-9802-c80f3ba0b22e)
发现 我这个极米遥控，按任何按键除了自己的keycode，还会再触发KEYCODE_UNKNOWN 我把代码注掉就好了
![image](https://github.com/lizongying/my-tv-0/assets/4637107/0b86ad2a-7a0a-4239-a194-77221c9ac911)
