### ISSUE TITLE
[BUG] 有个直播源导入后一直转圈，好像不能解析

### ISSUE THREAD

**Issue by lovekov** [lizongying/my-tv-0#37]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

http://223.110.241.139:6610/gitv/live1/G_JSCS/G_JSCS
这个链接，在VLC上导入可以正常播放

### 预期行为

希望开发者能优化一下

### 实际行为

目前没法播放
![微信图片_20240510201829](https://github.com/lizongying/my-tv-0/assets/25841123/73fca506-698f-4e9c-bbe2-873d8be50c5d)

### UI / OS

魅族16srpo

### Android 版本

10

**Comment by lovekov** [comment]
这个链接，需要移动的网才能播放。

**Comment by lizongying** [comment]
我的網絡就是移動，根本連不上

➜  ~ curl -v http://223.110.241.139:6610/gitv/live1/G_JSCS/G_JSCS  
*   Trying 223.110.241.139:6610...
* connect to 223.110.241.139 port 6610 failed: Operation timed out
* Failed to connect to 223.110.241.139 port 6610 after 75003 ms: Couldn't connect to server
* Closing connection
curl: (28) Failed to connect to 223.110.241.139 port 6610 after 75003 ms: Couldn't connect to server
