### ISSUE TITLE
[BUG] 在线源错误

### ISSUE THREAD

**Issue by 7noemo** [lizongying/my-tv-0#39]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

无法添加这个地址的在线源，但是把文件下载到本地导入又能正常读取
在线源地址(任意一行都不行)
`  https://ghproxy.net/https://raw.githubusercontent.com/ssili126/tv/main/itvlist.txt
  https://raw.githubusercontent.com/ssili126/tv/main/itvlist.txt`

### 预期行为

链接失败

### 实际行为

链接失败

### UI / OS

当贝投影

### Android 版本

10

**Comment by HonPhinXu1995** [comment]
https://raw.githubusercontent.com/Ftindy/IPTV-URL/main/hbgd.m3u

这个源地址也一直转圈

**Comment by linzzzzllll** [comment]
http://www.stream-link.org/stream-link.m3u这也不行

**Comment by lizongying** [comment]
@7noemo 自測，可以導入並播放。可能是網絡的問題，我這很卡。

**Comment by lizongying** [comment]
@linzzzzllll 401 無法訪問

**Comment by lizongying** [comment]
@HonPhinXu1995 視頻播放不了
