### ISSUE TITLE
开放插件商城功能 

### ISSUE THREAD

**Issue by gonjudaren** [lizongying/my-tv-0#4]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

方便维护 由不同的程序员去开发ui或者其他的插件 然后上传到插件库或者商店里 供用户自己选择 增加可玩性 

### 解决方案

类似于kodi
![R-C](https://github.com/lizongying/my-tv-0/assets/142286774/084e3d4e-7d57-41c9-bb77-68d09838ed49)

**Comment by lishengwei** [comment]
这个需求挺大的，估计作者不太会支持，还牵涉到支付吧。

**Comment by lizongying** [comment]
這個功能後續會考慮。

這個需求實際有很多問題待思考：
1. 多語言支持。目前主要還是國內用戶。
2. 皮膚。屬於錦上添花功能，在電視上還受到存儲空間和性能的限制。
3. 內容提供。這應該是最主要的功能，但如果上線到“商城”，可能會有法律風險。

綜上，意義不大。

即使我們看看kodi，可能是唯一做的比較好的了，但我為什麼不會用呢？
1. 操作複雜，可能是為了插件做出了妥協。操作一番後，甚至不知道自己在哪。
2. 插件很多，但想要的基本沒有。
3. 閃退等bug。

所以，插件功能先緩緩。
