### ISSUE TITLE
[BUG] 配置完直播地址源后，并没有确认按键

### ISSUE THREAD

**Issue by joytianya** [lizongying/my-tv-0#41]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

配置完直播地址源后，并没有确认按键

### 预期行为

配置完直播地址源后，并没有确认按键

### 实际行为

配置完直播地址源后，并有确认按键

### 复现步骤

配置完直播地址源后，并没有确认按键

### UI / OS

xiaomi

### Android 版本

12

### 额外信息

配置完直播地址源后，并没有确认按键

**Comment by gsons** [comment]
臣附议

**Comment by lizongying** [comment]
左侧按钮确认
