### ISSUE TITLE
建议样式改成my-tv一样，然后可以自定义源就行了

### ISSUE THREAD

**Issue by maciakng** [lizongying/my-tv-0#45]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

这样会是播放器简单易用，界面简洁易操作

### 解决方案

修改界面和my-tv一样

**Comment by lizongying** [comment]
界面應該不是太重要。
不同樣式也好區分。
