### ISSUE TITLE
[FR] 你好，有计划兼容安卓4吗？

### ISSUE THREAD

**Issue by bobpang2020** [lizongying/my-tv-0#47]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

安卓4的电视还有好多人，请问有计划兼容安卓4吗？

**Comment by lizongying** [comment]
有计划，但可能等等。

**Comment by dxxjg** [comment]
已有复刻实现了对android 4.2~4.3的兼容。
https://github.com/vrichv/my-tv-0/releases/tag/v1.2.8-jb3

能不能检查代码后，直接拉取进来。
