### ISSUE TITLE
当我使用这个.m3u文件作为本地视频源时，只能点选央视频道，其它频道无法点选[BUG] 

### ISSUE THREAD

**Issue by wangyupo** [lizongying/my-tv-0#48]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

在平板上，通过网络配置地址，在浏览器使用这个.m3u文件作为视频源，导入成功后，重启my-tv-0，点击左侧出现直播列表，点选“卫视频道”其中任何一个，无反应，但是点选“央视频道”可以。（视频源是IPV6的）

### 预期行为

点不同分组的频道应该都能加载直播

### 实际行为

只有点“央视频道”才能加载直播，其它分组不可以

### 复现步骤

1、将附件（iptv.txt）尾缀改为.m3u，并传输到平板本地
2、打开my-tv-0
3、使用“网络配置”，上传.m3u文件
4、上传成功后，重启my-tv-0
5、调出频道列表，尝试播放非“央视频道”的分组
[iptv.txt](https://github.com/lizongying/my-tv-0/files/15367438/iptv.txt)

### UI / OS

XIAOMI

### Android 版本

12

**Comment by lizongying** [comment]
是因為你的分組不連續造成的，比如央視分佈在不同位置。
在1.2.4解決了。
