### ISSUE TITLE
[FR] 老大俺来了，这回可以自己加源啦！

### ISSUE THREAD

**Issue by ashsteins** [lizongying/my-tv-0#5]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 LibChecker 的初衷。

### 改进目的

挺好，俺去弄点海外的源看

**Comment by lizongying** [comment]
“我的电视·〇”，可以使用[我的电视·服务](https://github.com/lizongying/my-tv-server)配置视频源。
