### ISSUE TITLE
[BUG] TVList.setPosition 存在潜在的越界问题

### ISSUE THREAD

**Issue by dyccsxg** [lizongying/my-tv-0#50]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

TVList.setPosition 可能存在越界问题：如下图当 if 条件成立时，前一行 log 日志中 getTVModel(position) 就已经越界了。

![image](https://github.com/lizongying/my-tv-0/assets/5917980/e79aee9e-e568-44b3-9234-a3d24ad0ebfe)

### 预期行为

无越界崩溃问题

### 实际行为

当越界时APP崩溃

### UI / OS

华为

### Android 版本

HarmonyOS 2.0

**Comment by lizongying** [comment]
下個版本修復
