### ISSUE TITLE
[FR] 联通网络在家里用路由器一直加载视频源，播放不了，其他换到手机移动网络直接播放，能不能选取写通用源或者联通网路可以播放的

### ISSUE THREAD

**Issue by love19791126** [lizongying/my-tv-0#54]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

联通网络在家里用路由器一直加载视频源，播放不了，其他换到手机移动网络直接播放，能不能选取写通用源或者联通网路可以播放的

**Comment by lizongying** [comment]
請自行配置直播源
