### ISSUE TITLE
[BUG] .m3u文件部分分组无法播放

### ISSUE THREAD

**Issue by wangyupo** [lizongying/my-tv-0#55]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

我更新了最新版本的my-tv-0，使用本地服务上传了.m3u文件，但是大多数频道都无法播放，唯独浙江分组可以播放。

我的m3u来自于 [fanmingming 大佬维护的仓库](https://github.com/fanmingming/live/blob/main/tv/m3u/ipv6.m3u)

### 预期行为

各分组应该都能播放。

### 实际行为

现在只有浙江分组可以播放

### 复现步骤

1、下载最新版本的my-tv-0
2、使用本地服务上传.m3u文件（将 iptv20240607.txt 重命名为 iptv20240607.m3u）
3、出现文件上传成功提示后，重启my-tv-0
4、打开my-tv-0，调出频道菜单，只能播放浙江分组，其它分组大多数都是黑屏，一直转圈。
附件：[iptv20240607.txt](https://github.com/user-attachments/files/15781012/iptv20240607.txt)

### UI / OS

TCL

### Android 版本

12

### 额外信息

之前提过一个类似的issue，不知道是不是一样的原因？[当我使用这个.m3u文件作为本地视频源时，只能点选央视频道，其它频道无法点选[BUG]](https://github.com/lizongying/my-tv-0/issues/48)

**Comment by lizongying** [comment]
不是之前的原因。應該是你的網絡不支持ipv6
