### ISSUE TITLE
[BUG] 1.2.3一1.2.6版本组播流无法播放

### ISSUE THREAD

**Issue by wztx** [lizongying/my-tv-0#59]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

1.0.9-1.2.2版本组播流能正常播放，1.2.3版本开始无法播放，连转成单播后都无法播放

### 预期行为

正常播放

### 实际行为

无法播放

### UI / OS

Sony/oneplus

### Android 版本

TV-9/PHONE-13

**Comment by lizongying** [comment]
可以試試 1.2.8

**Comment by wztx** [comment]
> 可以試試 1.2.8

感谢大佬，已经能正常播放
