### ISSUE TITLE
[BUG] 不能保存上次的频道，每次进去都是cctv1

### ISSUE THREAD

**Issue by tallguess** [lizongying/my-tv-0#6]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

v1.0.1

### Bug 描述

如题，还有收藏功能不能用？

### 预期行为

？

### 实际行为

？

### UI / OS

小米电视

### Android 版本

6

**Comment by lizongying** [comment]
[1.0.3](https://github.com/lizongying/my-tv-0/releases/tag/v1.0.3) 已解决保存上次频道

**Comment by tallguess** [comment]
> [1.0.3](https://github.com/lizongying/my-tv-0/releases/tag/v1.0.3) 已解决保存上次频道

更新后可以了，收藏功能还是不懂用

**Comment by lizongying** [comment]
收藏功能已支持
