### ISSUE TITLE
[FR] 作者请教一下，我需要把自己的直播源地址添加进入APP内作为他默认地址，请问我需要把地址填到源码哪里？

### ISSUE THREAD

**Issue by loveu5522** [lizongying/my-tv-0#61]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

想把自己的个人源添加到APP内，作为他的默认源，请问我需要修改源码的哪个文件呢？

**Comment by Hikari404** [comment]
我也想知道，[my-tv-server]运行给了个本地地址，打开应用两眼茫茫

**Comment by lizongying** [comment]
可以在這裡修改
```
       get() = sp.getString(KEY_CONFIG,
            "")
```
