### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by x0829** [lizongying/my-tv-0#64]
家里电信宽带，大部分频道不能观看，切换数据流量后没问题，该怎么解决啊？

**Comment by luciferslla** [comment]
一样，宽带只有浙江的几个台可以看，数据流量基本都可以。有谁知道解决方法吗？

**Comment by syhufo** [comment]
+1,我是全部频道都看不了了

**Comment by lipanzjzs** [comment]
> 一样，宽带只有浙江的几个台可以看，数据流量基本都可以。有谁知道解决方法吗？

只有浙江台用的是IPV4源，其他都是IPV6,你要先确认你的运营商有没有给你开IPV6，然后路由器有没有把IPV6关掉。

**Comment by lizongying** [comment]
參考@lipanzjzs 另外標題儘量表明主旨
