### ISSUE TITLE
[FR] 希望能增加公网配置地址功能

### ISSUE THREAD

**Issue by iviviviviviv** [lizongying/my-tv-0#67]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

希望能增加公网配置地址功能，帮外地父母配置地址太痛苦了，输到一半配置界面就消失了

**Comment by lizongying** [comment]
這需要公網服務器支持。
不知道短鏈接一類的能否有幫助。
