### ISSUE TITLE
CHC高清电影、CHC家庭影院、CHC动作电影无法观看[BUG] 

### ISSUE THREAD

**Issue by Adjang** [lizongying/my-tv-0#68]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

CHC高清电影、CHC家庭影院、CHC动作电影无法观看，都是黑屏，盼望尽快解决。

### 预期行为

上述三个频道黑屏无法播放

### 实际行为

上述三个频道黑屏无法播放

### UI / OS

华为手机nova10

### Android 版本

鸿蒙

### 额外信息

手机是鸿蒙，但是其他频道都可以播放

**Comment by lizongying** [comment]
視頻源問題，可以自己編輯視頻源
