### ISSUE TITLE
[FR] 强烈建议支持Android4.4.2，老电视急需

### ISSUE THREAD

**Issue by Luoyoung** [lizongying/my-tv-0#7]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

支持Android4.4.2

**Comment by kimwang1978** [comment]
强烈建议老电视扔了  ：）

**Comment by lfm09** [comment]
荣耀盒子也不能安装，提示解析失败，系统也是4.4.2

**Comment by chinawbf** [comment]
应用无法安装：INSTALL_FAILED_OLDER_SDK,天猫魔盒16s，那个mytv能用。这个0就不能运行

**Comment by chinawbf** [comment]
defaultConfig {
        applicationId "com.lizongying.mytv"
        minSdk 21
        targetSdk 33
        versionCode VersionCode()
        versionName VersionName()
------------------------------------------------------------
minSdk 21

------------------------------
咱自己也不会编译apk啊

**Comment by Luoyoung** [comment]
高版本安卓有其他选择，比如tivimate之类的，低版本安卓没其他选择，如果作者支持，低版本只能用mytv0，也是很多潜在用户。

**Comment by ui1840** [comment]
确实，国内的电视大多都是4.4的版本，如果从6开始的话，好多用户都被抛弃了，而且这个市场很大的，期望作者可以响应这个需求，感谢，

**Comment by AppleMate60pro** [comment]
对于这个TVbox类的播放器不是功能更完善吗？还是你们以为用这个自定义源也能像通用版那样换台快？别傻了，你能有加载快的源？现在这个政策下

**Comment by lizongying** [comment]
在功能基本完善後會考慮兼容問題，目前暫時支持到安卓5吧。
