### ISSUE TITLE
配置地址bug

### ISSUE THREAD

**Issue by for7GG** [lizongying/my-tv-0#73]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

点击配置地址按钮，地址未保存，还是默认的地址

### 预期行为

按照用户输入的地址保存

### 实际行为

实际还是默认的地址导致无法播放

### UI / OS

Xiaomi

### Android 版本

14

**Comment by for7GG** [comment]
1.3.0是正常的，请修复这个bug

**Comment by lizongying** [comment]
可能是請求失敗了

**Comment by lizongying** [comment]
請使用最新版本
