### ISSUE TITLE
[BUG] 升级或者安装后，内置源被重置，导入m3u文件后，恢复自己的源，但是重新打开app后，又变成内置源了，设置中没有开启自动更新源

### ISSUE THREAD

**Issue by lovekov** [lizongying/my-tv-0#74]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

内置源被重置，导入m3u文件后，恢复自己的源，但是重新打开app后，又变成内置源了，设置中没有开启自动更新源。回退到1.3.0就没有这个bug了

### 预期行为

不会每次打开后自动更新内置源，替换之前网页上自己上传的m3u文件源

### 实际行为

实际上每次进入app，都会更新内置源，替换自己上传的m3u文件源

### UI / OS

flyme,tcl

### Android 版本

10

**Comment by lizongying** [comment]
好像是有这个问题。导入文件后，配置地址还是空的。再次打开的时候会应用默认的配置地址，导致自定义被覆盖。
可能的方案，
1. 关闭“启动应用后自动更新数据源”
2. 导入文件后，修改配置地址，防止二次覆盖。你可以随便写一个地址进行占位。

注意，新版本1.3.2会有个问题，如果上传了文件，点击应用配置，会应用配置地址，所以你还是得修改配置地址。下个版本修再复了。

**Comment by lizongying** [comment]
可以試試最新版本 是否有類似情況
