### ISSUE TITLE
[FR] 关于电视台图标及背景颜色的议题

### ISSUE THREAD

**Issue by dxxjg** [lizongying/my-tv-0#76]
### 检查清单

- [X] 之前没有人提交过类似或相同的功能请求。
- [X] 这个建议不会背离 我的电视·〇 的初衷。

### 改进目的

前提：频道列表页的背景是深色，频道单页显示条采用的是“”图标背景白色+文字背景深色”的组合。
问题：这种设计对于彩色图标来说是完全没问题，但是对于 白色系/透明系 图标就完蛋了（比如：CCTV系、NewTV系、山西卫视、五星体育、以及北京BRTV图标后边近乎透明的文字横条……）。

**下面以CCTV1举例，准备了4款样式：**

第1款： https://raw.githubusercontent.com/fanmingming/live/main/tv/CCTV1.png
效果：离得近看着还凑合。稍微远一点看，就剩一个红色的C。
![1](https://github.com/user-attachments/assets/3393a554-05c5-4df4-8b60-71aa81173247)

第2款： https://raw.githubusercontent.com/drangjchen/IPTV/main/Logo/CCTV1-light.png
效果：这个是真真的只有一个红色的C，根本没法看。
![2](https://github.com/user-attachments/assets/cc769386-c40b-4252-b4a0-78b9d2591089)

第3款： https://assets.livednow.com/logo/CCTV1.png
效果：在此处看着稍微一般，背景还是太白。（当前CCTV各台左上角用的标就是这一款）
![3](https://github.com/user-attachments/assets/576c83c3-0fa5-46cd-a300-308d54865a84)

第4款： https://raw.githubusercontent.com/echolin73/logo/main/tvg-logo/CCTV1.png
效果：无疑，这个是在单页的表现最好。
![4](https://github.com/user-attachments/assets/e75d48aa-7a01-4f0b-89c4-8824bf830dcb)

**最后来看一下这4款在 频道列表页 的效果图：**  
很明显，最难看的是4，距离稍远看着是一坨坨的黑色。最好看的是1。而2和3的表现都很一般。
![0](https://github.com/user-attachments/assets/3bde221a-9ec3-498f-9692-166c4fa4a309)

**另外，看一下其他白色系台标的表现**
BRTV系列的文字横条和纯白色的第一财经的频道单页显示效果，惨不忍睹：
![5](https://github.com/user-attachments/assets/3cdc8745-0a48-44b7-b94a-19b4955cd9d9)     ![6](https://github.com/user-attachments/assets/cd74239c-fc46-425d-a6f9-03bbd674b7d7) 

### 解决方案

将频道单页显示条的图标背景区域也改为深色系。
既可以跟文字背景区融为一体，也可以中间分开为两个区域，都不难看。就可以使用1样式了，或者3样式也不错。

**Comment by lizongying** [comment]
如果圖標是用戶自定義的，圖標會很複雜。除非使用預製的，這和用戶的頻道匹配也是個問題。

**Comment by dxxjg** [comment]
> 如果圖標是用戶自定義的，圖標會很複雜。除非使用預製的，這和用戶的頻道匹配也是個問題。

台标无需内置。现在git有多个电视logo项目，直接调用特别方便。
现在的问题是，频道列表页是深色背景，而频道单页的显示条却是白色背景，两处的背景颜色反差太大，导致无法兼容显示白色系或黑色系图标。希望考虑：将频道单页的显示条也改为深色背景。

**Comment by lizongying** [comment]
新版本改為深色了

**Comment by dxxjg** [comment]
> 新版本改為深色了

大佬辛苦啦……
