### ISSUE TITLE
my-tv-0.1.3.5.11三个apk，有什么区别？

### ISSUE THREAD

**Issue by xaqingfeng** [lizongying/my-tv-0#82]
### 提需求前請檢查

- [X] 已檢查過需求列表，沒有人提過相同需求

### 需求建議

my-tv-0.1.3.5.11三个apk，有什么区别？

**Comment by ccav14** [comment]
字面理解，默认自带的源地址不同
china-mobile用的这个https://live.fanmingming.com/tv/m3u/itv.m3u
ipv6用的这个https://live.fanmingming.com/tv/m3u/ipv6.m3u

**Comment by lizongying** [comment]
@ccav14 是的
