### ISSUE TITLE
[BUG]安卓4.4版本，节目菜单字体太大。

### ISSUE THREAD

**Issue by jingtuz** [lizongying/my-tv-0#83]
### 提問題前請檢查

- [X] 已檢查過問題列表，沒有人提過相同問題
- [X] 軟件的最新版本依然沒有被修復

### 軟件版本

 v1.2.8kk6

### 電視品牌

I华为电视盒

### Android版本

安卓4'4'

### 問題描述

在安卓4.4电视盒子安装 my-tv-0)v1.2.8kk6版后，节目源菜单字体太大了，显示不全，希望修改一下。

**Comment by cqbf** [comment]
你发错位置了，兼容4.4的是 https://github.com/vrichv/my-tv-0

**Comment by lizongying** [comment]
#78
