### ISSUE TITLE
[BUG] 1.3.6 红米直接装完点app没有反应，1.3.5.11点开是白屏，右侧最上面选项是空白

### ISSUE THREAD

**Issue by love19791126** [lizongying/my-tv-0#85]
### 提問題前請檢查

- [X] 已檢查過問題列表，沒有人提過相同問題
- [X] 軟件的最新版本依然沒有被修復

### 軟件版本

1.3.6

### 電視品牌

红米

### Android版本

mui14

### 問題描述

1.3.6 红米直接装完点app没有反应，1.3.5.11点开是白屏，右侧最上面选项是空白

**Comment by lizongying** [comment]
#86
