### ISSUE TITLE
配置地址后读取不到节目列表

### ISSUE THREAD

**Issue by yalicez** [lizongying/my-tv-0#9]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

v1.0.1

### Bug 描述

在Windows中运行mytvserver，浏览器打开127.0.0.1:8000/0选中直播源文件后，点输出json后，在雷电模拟器运行mytvo，输入配置地址127.0.0.1:8000/0，读取不到节目列表，版本1.04

### 预期行为

应该读取到节目列表

### 实际行为

读取不到节目列表

### 复现步骤

见bug描述

### UI / OS

雷电模拟器

### Android 版本

9

### 额外信息

无

**Comment by lizongying** [comment]
你可以試試用局域網地址，如192.168.*.*

**Comment by lfm09** [comment]
感觉现在添加自定义节目源的方式太麻烦了，要是能通过读取本地文件就更方便

**Comment by henrycjchen** [comment]
在 gitee 上建个仓库就可以放自定义节目源了

**Comment by lizongying** [comment]
> 感觉现在添加自定义节目源的方式太麻烦了，要是能直接通过读取本地文件来添加台就更方便

特別是電視上，上傳文件對於部分設備和部分用戶還是比較困難的。添加地址相對簡單點。
