### ISSUE TITLE
[BUG] Release v1.3.7.11部分频道画面撕裂

### ISSUE THREAD

**Issue by smallprogram** [lizongying/my-tv-0#92]
### 提問題前請檢查

- [X] 已檢查過問題列表，沒有人提過相同問題
- [X] 軟件的最新版本依然沒有被修復

### 軟件版本

1.3.7.11

### 電視品牌

乐视Max55

### Android版本

基于Android 6.0的EUI8.0系统

### 問題描述

部分频道，画面抽搐，不居中。直播源来自本地iptv
![4ea7892a5fc6c9d6dcb2b103873dafd](https://github.com/user-attachments/assets/a58d33e5-cb89-4c83-9cad-f2a710888c16)
![de41ffad8b9561ae6df5e7c58ff6f71](https://github.com/user-attachments/assets/19e69053-38e0-4a9e-9a61-1c2772a3e0f8)

**Comment by akinaedison** [comment]
这个版本还是几率性闪退

**Comment by lizongying** [comment]
@smallprogram 這個問題暫時我還解決不了，在此也向各位開發者請教，如果有解決辦法，希望可以告知

**Comment by smallprogram** [comment]
> @smallprogram 這個問題暫時我還解決不了，在此也向各位開發者請教，如果有解決辦法，希望可以告知

好吧。。。。
