### ISSUE TITLE
[FR] 建议更新播放器版本到最新

### ISSUE THREAD

**Issue by 99477204** [lizongying/my-tv-0#96]
### 提需求前請檢查

- [X] 已檢查過需求列表，沒有人提過相同需求

### 需求建議

不知道开发者用的那个播放器，在有些设备上很多频道不能播放，建议更新播放器到最新版本。记得以前exo低版本的就很多频道不能播放

**Comment by lizongying** [comment]
版本已是最新。目前只支持硬解，部分格式無法播放。
