### ISSUE TITLE
[BUG] my-tv-0.1.3.7.11 ，提示播放错误

### ISSUE THREAD

**Issue by ebaogogo** [lizongying/my-tv-0#97]
### 提問題前請檢查

- [X] 已檢查過問題列表，沒有人提過相同問題
- [X] 軟件的最新版本依然沒有被修復

### 軟件版本

my-tv-0.1.3.7.11

### 電視品牌

华为智慧屏

### Android版本

鸿蒙2.0

### 問題描述

央视无法播放
卫视全部无法播放
香港凤凰可以播放

**Comment by ebaogogo** [comment]
https://github.com/andandroidor/ourtv/releases

**Comment by lizongying** [comment]
視頻源問題

**Comment by ebaogogo** [comment]
感谢你做的这个项目，让老人有电视看；建议你在设置菜单里，提供二维码让愿意支持你研发的人援助你的开发；
https://github.com/yaoxieyoulei/mytv-android/releases  这个好像也是基于你MYTV上做的，似乎做得不错，可以参考下；

**Comment by ebaogogo** [comment]
感谢你做的这个项目，让老人有电视看；建议你在设置菜单里，提供二维码让愿意支持你研发的人援助你的开发；
https://github.com/yaoxieyoulei/mytv-android/releases  这个好像也是基于你MYTV上做的，似乎做得不错，可以参考下；
