### ISSUE TITLE
[FR] support RTMP protocol URL

### ISSUE THREAD

**Issue by mk386** [lizongying/my-tv-0#98]
### 提需求前請檢查

- [X] 已檢查過需求列表，沒有人提過相同需求

### 需求建議

1. 支援 RTMP 協議
2. 似乎可利用 ExoPlayer 庫支援

**Comment by lizongying** [comment]
[Release v1.3.8.1](https://github.com/lizongying/my-tv-0/releases/tag/v1.3.8.1) 已支持
