### ISSUE TITLE
[BUG] 使用txt格式类型的多分组文件时，只能生成一个分组，分组名为txt最后一个组名，所有频道均在此分组里

### ISSUE THREAD

**Issue by crarm** [lizongying/my-tv-0#99]
### 提問題前請檢查

- [X] 已檢查過問題列表，沒有人提過相同問題
- [X] 軟件的最新版本依然沒有被修復

### 軟件版本

1.3.7.11

### 電視品牌

华为

### Android版本

9

### 問題描述

使用txt格式类型的多分组文件时，只能生成一个分组，分组名为txt最后一个组名，所有频道均在此分组里

**Comment by wolopo** [comment]
我也遇到这个问题，只有最后一个频道组是正确的。耐心等待作者修复，多谢

**Comment by lizongying** [comment]
@crarm 方便的話，發給我一下txt文件，方便測試修改。lizongying@msn.com

**Comment by lizongying** [comment]
感謝@fluidcat  他的修改應該是沒問題的，可以試試最新版。

**Comment by crarm** [comment]
最新版已修复！！1
